myexecle:myexecle.c
	gcc myexecle.c -o myexecle
Execl:Execl.c
	gcc Execl.c -o Execl
Wait:Wait.c
	gcc Wait.c -o Wait
creatpcb:creatpcb.c
	gcc creatpcb.c -o creatpcb
environ:environ.c
	gcc environ.c -o environ
